/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function serialize(value: any): Array<number>
export declare function deserialize(buffer: Array<number>): any
export declare function isValidFlexbuffer(buffer: Array<number>): boolean
export declare class FlexBuffer {
  constructor()
  serialize(value: any): void
  deserialize(): any
  getBuffer(): Array<number>
  static fromBuffer(buffer: Array<number>): FlexBuffer
  size(): number
}

// Convenience aliases
export declare const isValid: typeof isValidFlexbuffer
export declare const serializeToFlexbuffer: typeof serialize
export declare const deserializeFromFlexbuffer: typeof deserialize