name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            name: darwin-x64
          - os: macos-latest  
            target: aarch64-apple-darwin
            name: darwin-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: win32-x64-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x64-gnu

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Build
        run: |
          bun install
          bun run build
      
      - name: List files
        shell: bash
        run: ls -la *.node || echo "No .node files found"
      
      - name: Rename binary
        shell: bash
        run: |
          for f in *.node; do
            if [ -f "$f" ]; then
              target_name="flexbuffers-js.${{ matrix.name }}.node"
              if [ "$f" != "$target_name" ]; then
                mv "$f" "$target_name"
                echo "Renamed $f to $target_name"
              else
                echo "File $f already has correct name"
              fi
            fi
          done
          ls -la *.node
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            flexbuffers-js.${{ matrix.name }}.node

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Prepare release files
        run: |
          find artifacts -name "*.node" -exec cp {} . \;
          ls -la *.node
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            flexbuffers-js.*.node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}